import type { Metadata } from "next";
import Image from "next/image";
import { Card, SectionTitle } from "@/components/ui/Card";
import { ButtonLink } from "@/components/ui/Button";
import { CTABand, PageHero } from "@/components/marketing/Sections";
import { Avatar } from "@/components/brand/DealerMark";
import { IconBuilding, IconMail, IconMapPin, IconPhone } from "@/components/icons";
import { marketingImages } from "@/lib/images";

export const metadata: Metadata = {
  title: "About",
  description:
    "Way More is a St. Louis company building a better way to sell your car — dealer competition, no fees, and no strangers at your door.",
};

const VALUES = [
  {
    title: "Say the real number",
    body: "Estimates are ranges because that's what they are. Offers are firm because a number you can't rely on isn't an offer. We'd rather under-promise than explain a surprise at pickup.",
  },
  {
    title: "The seller is the customer",
    body: "Dealers pay us, but they aren't who we work for. That's why dealers never get your phone number, why every offer is no-obligation, and why we remove dealers who renegotiate.",
  },
  {
    title: "Local beats national",
    body: "A dealer twenty minutes away knows what your car retails for on their lot this month. That local knowledge is worth more to you than an algorithm in another state.",
  },
];

const TEAM = [
  { name: "Justin Higginbotham", role: "Founder", initials: "JH", bio: "Spent fifteen years inside dealership operations watching good cars get bought badly." },
  { name: "Alexis Moore", role: "Head of Operations", initials: "AM", bio: "Runs the weekly event, dealer verification, and every payout that leaves the building." },
  { name: "Dana Kessler", role: "Dealer Partnerships", initials: "DK", bio: "Brings dealers onto the platform and keeps the bidding honest." },
];

export default function AboutPage() {
  return (
    <>
      <PageHero
        eyebrow="About"
        title={
          <>
            Built in St. Louis,
            <br />
            for people selling cars.
          </>
        }
        lead="Way More started with a simple observation: the person selling the car is the only one in the transaction without any leverage. We built a marketplace that hands it back."
        image={marketingImages.dealerLot}
        imagePosition="center 40%"
      />

      {/* ========================================================== story */}
      <section className="bg-surface py-16 sm:py-20">
        <div className="container-page grid lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <div className="relative aspect-[4/3] rounded-2xl overflow-hidden ring-1 ring-line shadow-card">
            <Image
              src={marketingImages.working}
              alt="A Way More team member reviewing listings"
              fill
              sizes="(max-width: 1024px) 100vw, 45vw"
              className="object-cover"
            />
          </div>
          <div>
            <h2 className="text-[30px] sm:text-[36px] leading-[1.1]">Why we started</h2>
            <div className="mt-4 h-[3px] w-16 rounded-full bg-lime-400" />
            <div className="mt-6 space-y-4 text-[15.5px] leading-relaxed text-body">
              <p>
                If you have sold a car recently, you know the options. Trade it in and accept
                whatever the dealer offers against a new purchase. Punch your details into a
                national site and take one number generated by a model that has never seen your
                car. Or list it privately, and spend three weekends fielding messages from people
                who never show up.
              </p>
              <p>
                Meanwhile, the dealers twenty minutes from your house are actively short on
                inventory and paying auction fees to buy cars exactly like yours, sight unseen,
                from three states away.
              </p>
              <p className="text-heading font-medium">
                Way More closes that gap. Your car goes in front of every verified dealer in your
                market at the same time, once a week, and they bid against each other for it. You
                pick the offer you like — or none of them.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ========================================================= values */}
      <section className="bg-paper py-16 sm:py-20">
        <div className="container-page">
          <SectionTitle
            eyebrow="How we operate"
            title="Three things we don't compromise on"
          />
          <div className="mt-11 grid gap-5 md:grid-cols-3">
            {VALUES.map((v, i) => (
              <Card key={v.title}>
                <span className="font-display font-extrabold text-[28px] text-lime-500 leading-none">
                  0{i + 1}
                </span>
                <h3 className="mt-3.5 text-[17px] leading-snug">{v.title}</h3>
                <p className="mt-2 text-[14px] leading-relaxed text-body">{v.body}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* =========================================================== team */}
      <section className="bg-surface py-16 sm:py-20">
        <div className="container-page">
          <SectionTitle title="The people behind it" />
          <div className="mt-11 grid gap-5 md:grid-cols-3">
            {TEAM.map((m) => (
              <Card key={m.name} className="text-center">
                <div className="flex justify-center">
                  <Avatar initials={m.initials} size={64} tone="muted" />
                </div>
                <h3 className="mt-4 text-[16.5px]">{m.name}</h3>
                <p className="mt-0.5 text-[13px] font-semibold text-lime-600">{m.role}</p>
                <p className="mt-3 text-[13.5px] leading-relaxed text-body">{m.bio}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ======================================================== contact */}
      <section className="bg-paper py-16 sm:py-20">
        <div className="container-page grid lg:grid-cols-2 gap-10 items-start">
          <div>
            <h2 className="text-[30px] sm:text-[36px] leading-[1.1]">Get in touch</h2>
            <p className="mt-4 text-[15.5px] leading-relaxed text-body max-w-md">
              Questions about a listing, a payout, or bringing your dealership onto the platform —
              we answer everything from the same office.
            </p>
            <dl className="mt-8 space-y-4">
              {[
                { icon: <IconPhone size={19} />, label: "Phone", value: "(314) 555-0123", href: "tel:+13145550123" },
                { icon: <IconMail size={19} />, label: "Email", value: "hello@trywaymore.com", href: "mailto:hello@trywaymore.com" },
                { icon: <IconMapPin size={19} />, label: "Office", value: "4212 Lindell Blvd, St. Louis, MO 63108", href: null },
              ].map((c) => (
                <div key={c.label} className="flex gap-3.5">
                  <span className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-xl bg-mint-50 text-ink-800 ring-1 ring-lime-200">
                    {c.icon}
                  </span>
                  <div>
                    <dt className="text-[12px] font-semibold uppercase tracking-[0.1em] text-muted">
                      {c.label}
                    </dt>
                    <dd className="text-[15px] text-heading font-medium mt-0.5">
                      {c.href ? (
                        <a href={c.href} className="hover:text-lime-600 transition-colors">
                          {c.value}
                        </a>
                      ) : (
                        c.value
                      )}
                    </dd>
                  </div>
                </div>
              ))}
            </dl>
          </div>

          <Card className="!bg-ink-950 !ring-ink-800">
            <span className="grid size-11 place-items-center rounded-xl bg-white/10 text-lime-400 ring-1 ring-white/15">
              <IconBuilding size={24} />
            </span>
            <h3 className="mt-4 text-[19px] text-white">Are you a dealer?</h3>
            <p className="mt-2.5 text-[14.5px] leading-relaxed text-white/65">
              Way More gives you locally sourced inventory from real sellers in your own market —
              no membership fees, no subscriptions, and transparent timed events every Wednesday.
            </p>
            <ul className="mt-5 space-y-2.5">
              {[
                "Free to browse this week's event",
                "Pay only on the vehicles you win",
                "Verified sellers, disclosed condition",
              ].map((li) => (
                <li key={li} className="flex gap-2.5 text-[14px] text-white/80">
                  <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-lime-400" />
                  {li}
                </li>
              ))}
            </ul>
            <div className="mt-6">
              <ButtonLink href="/dealer" fullWidth withArrow>
                Visit the dealer portal
              </ButtonLink>
            </div>
          </Card>
        </div>
      </section>

      <CTABand />
    </>
  );
}
